### ISSUE TITLE
Configure binary caching for fast startup

### ISSUE THREAD

**Issue by apt-get-coke** [apt-get-coke/nix-services-action#25]
### Goal
Ensure PostgreSQL, Redis, and other dependencies are fetched from binary caches (not built from source), making the action fast even on first run.

### Implementation

1. **Configure trusted binary caches**:
```bash
# In start.sh, before running nix-shell
export NIX_CONFIG="
substituters = https://cache.nixos.org https://devenv.cachix.org https://nix-community.cachix.org
trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= devenv.cachix.org-1:w1cLUi8dv3hnoSPGAuibQv+f9TZLr6cv/Hm9XgU50cw= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=
"
```

2. **Add GitHub Actions cache integration**:
```yaml
# Document in README how to cache Nix store
- uses: actions/cache@v3
  with:
    path: |
      /nix/store
      /nix/var/nix/db/sqlite
      ~/.cache/nix
    key: nix-${{ runner.os }}-${{ hashFiles('**/flake.lock') }}
```

3. **Pre-fetch common packages** (optional optimization):
```bash
# In start.sh, pre-fetch in background while starting
nix-shell -p postgresql_15 redis --run "echo 'Packages ready'" &
```

### Performance Targets
- First run (no cache): < 60 seconds to download binaries
- Subsequent runs (with cache): < 5 seconds to start services
- Binary cache hit rate: > 95% for common packages

### Benefits
- PostgreSQL (~100MB) downloaded as binary, not compiled
- Redis (~10MB) downloaded as binary
- Leverages Nix's global binary cache infrastructure
- Integrates with GitHub Actions caching

### Testing
- Measure time to start services on fresh runner
- Verify binary substitution is used (not source builds)
- Test with GitHub Actions cache enabled/disabled

### Documentation
Add to README:
- How to configure GitHub Actions cache
- Expected performance metrics  
- How to verify binary cache is working
- Troubleshooting slow downloads
