### ISSUE TITLE
Add comprehensive examples for different runner types

### ISSUE THREAD

**Issue by apt-get-coke** [apt-get-coke/nix-services-action#26]
### Goal
Provide clear examples showing how nix-services-action works across different GitHub Actions environments, demonstrating its portability and ease of use.

#### 1. GitHub-hosted runner (ubuntu-latest)
```yaml
name: Test on GitHub Runner
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Cache Nix installation
      - uses: actions/cache@v3
        with:
          path: |
            /nix
            ~/.nix-profile
          key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix') }}
      
      # Start services (Nix will be auto-installed if needed)
      - uses: apt-get-coke/nix-services-action@v2
        with:
          services: postgresql redis
          config: |
            {
              "postgresql": {"version": "15"},
              "redis": {"version": "7.2"}
            }
      
      - run: |
          psql -h localhost -U postgres -c "SELECT version();"
          redis-cli ping
```

#### 2. Self-hosted runner with Nix
```yaml
name: Test on Nix Runner
on: [push]

jobs:
  test:
    runs-on: [self-hosted, nix]
    steps:
      - uses: actions/checkout@v4
      
      # Services start instantly (Nix already available)
      - uses: apt-get-coke/nix-services-action@v2
        with:
          services: postgresql redis
          resource-profile: performance
      
      - run: |
          # Your tests here
          pytest
```

#### 3. Matrix testing across multiple versions
```yaml
strategy:
  matrix:
    postgres: [14, 15, 16]
    redis: [7.0, 7.2]

steps:
  - uses: apt-get-coke/nix-services-action@v2
    with:
      services: postgresql redis
      config: |
        {
          "postgresql": {"version": "${{ matrix.postgres }}"},
          "redis": {"version": "${{ matrix.redis }}"}
        }
```

### Migration Guide from Docker Services

Show before/after:

**Before (Docker):**
```yaml
services:
  postgres:
    image: postgres:15
    env:
      POSTGRES_PASSWORD: postgres
    options: >-
      --health-cmd pg_isready
      --health-interval 10s
```

**After (Nix):**
```yaml
steps:
  - uses: apt-get-coke/nix-services-action@v2
    with:
      services: postgresql
      config: |
        {"postgresql": {"version": "15"}}
```

### Performance Comparison

Document the benefits:
- First run: Nix install + binary cache (~90 seconds)
- Subsequent runs: Instant startup (Nix store cached)
- Memory usage: Lower than Docker containers
- Disk usage: Shared Nix store (deduplication)

### Troubleshooting Section

Common issues and solutions:
- Nix installation failures
- Binary cache configuration
- Service startup timeouts
- Permission issues

### README Structure
1. Quick Start
2. Examples (above)
3. Configuration Reference
4. Performance Tips
5. Migration Guide
6. Troubleshooting
7. Contributing
